// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace PostgRESTSharp.Commands.GenerateRESTRoutes.Templates {
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    
    public partial class NancyRESTRoute : NancyRESTRouteBase {
        
        public virtual string TransformText() {
            this.GenerationEnvironment = null;
            
            #line 6 ""
            this.Write("using Nancy;\nusing Nancy.ModelBinding;\nusing System.Net.Http;\nusing Newtonsoft.Json;\nusing System.Collections.Generic;\nusing System.Linq;\nusing PostgRESTSharp.Shared;\nusing ");
            
            #line default
            #line hidden
            
            #line 13 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelNamespace));
            
            #line default
            #line hidden
            
            #line 13 ""
            this.Write(";\n\nnamespace ");
            
            #line default
            #line hidden
            
            #line 15 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(Namespace));
            
            #line default
            #line hidden
            
            #line 15 ""
            this.Write(" \n{\n    public class ");
            
            #line default
            #line hidden
            
            #line 17 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            
            #line 17 ""
            this.Write(" : NancyModule\n    {\n    \tpublic ");
            
            #line default
            #line hidden
            
            #line 19 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            
            #line 19 ""
            this.Write("(IRestLinkBuilder linkBuilder) \n    \t{\n    \t\tGet[\"/");
            
            #line default
            #line hidden
            
            #line 21 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(CollectionRouteUrl));
            
            #line default
            #line hidden
            
            #line 21 ""
            this.Write("\", true] = async (ctx, ct) =>\n    \t\t{\n    \t\t\tvar client = new HttpClient();\n\t\t\t\tstring route = \"http://DEVB-PG01:3000/");
            
            #line default
            #line hidden
            
            #line 24 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(UnderlyingCollectionRouteUrl));
            
            #line default
            #line hidden
            
            #line 24 ""
            this.Write("?order=");
            
            #line default
            #line hidden
            
            #line 24 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(PrimaryKeyColumnName));
            
            #line default
            #line hidden
            
            #line 24 ""
            this.Write(".asc\";\n    \t\t\tvar res = await client.GetAsync(route);\n    \t\t\tvar content = await res.Content.ReadAsStringAsync();\n\t\t\t\tvar models = JsonConvert.DeserializeObject<List<");
            
            #line default
            #line hidden
            
            #line 27 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(GETModelName));
            
            #line default
            #line hidden
            
            #line 27 ""
            this.Write(">>(content);\n\t\t\t\tforeach(var model in models)\n\t\t\t\t{\n\t\t\t\t\tUrl url = new Url();\n\t\t\t\t\turl.HostName = this.Request.Url.HostName;\n\t\t\t\t\turl.Port = this.Request.Url.Port;\n\t\t\t\t\turl.BasePath = this.Request.Url.Path;\n\t\t\t\t\turl.Path = \"/\" + model.GetPrimaryKeyValue();\n\t\t\t\t\tmodel.BuildLinks(linkBuilder, url);\n\t\t\t\t}\n\n\t\t\t\treturn this.Negotiate.WithModel(models).WithHeader(\"Accept\",\"application/json\");\n    \t\t};\n\n    \t\tGet[\"/");
            
            #line default
            #line hidden
            
            #line 41 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(CollectionRouteUrl));
            
            #line default
            #line hidden
            
            #line 41 ""
            this.Write("/{");
            
            #line default
            #line hidden
            
            #line 41 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(PrimaryKeyColumnName));
            
            #line default
            #line hidden
            
            #line 41 ""
            this.Write("}\", true] = async (ctx, ct) =>\n    \t\t{\n    \t\t\tvar client = new HttpClient();\n\t\t\t\tstring route = string.Format(\"http://DEVB-PG01:3000/");
            
            #line default
            #line hidden
            
            #line 44 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(UnderlyingCollectionRouteUrl));
            
            #line default
            #line hidden
            
            #line 44 ""
            this.Write("?");
            
            #line default
            #line hidden
            
            #line 44 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(PrimaryKeyColumnName));
            
            #line default
            #line hidden
            
            #line 44 ""
            this.Write("=eq.{0}\", ctx.");
            
            #line default
            #line hidden
            
            #line 44 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(PrimaryKeyColumnName));
            
            #line default
            #line hidden
            
            #line 44 ""
            this.Write(");\n    \t\t\tvar res = await client.GetAsync(route);\n    \t\t\tvar content = await res.Content.ReadAsStringAsync();\n\n\t\t\t\tvar models = JsonConvert.DeserializeObject<List<");
            
            #line default
            #line hidden
            
            #line 48 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(GETModelName));
            
            #line default
            #line hidden
            
            #line 48 ""
            this.Write(">>(content);\n\t\t\t\tvar model = models.First();\n\t\t\t\tmodel.BuildLinks(linkBuilder, this.Request.Url);\n\t\t\t\treturn this.Negotiate.WithModel(model).WithHeader(\"Accept\",\"application/json\");\n    \t\t};\n    \t}\n    }\n}");
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        public virtual void Initialize() {
        }
    }
    
    public class NancyRESTRouteBase {
        
        private global::System.Text.StringBuilder builder;
        
        private global::System.Collections.Generic.IDictionary<string, object> session;
        
        private global::System.CodeDom.Compiler.CompilerErrorCollection errors;
        
        private string currentIndent = string.Empty;
        
        private global::System.Collections.Generic.Stack<int> indents;
        
        private ToStringInstanceHelper _toStringHelper = new ToStringInstanceHelper();
        
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session {
            get {
                return this.session;
            }
            set {
                this.session = value;
            }
        }
        
        public global::System.Text.StringBuilder GenerationEnvironment {
            get {
                if ((this.builder == null)) {
                    this.builder = new global::System.Text.StringBuilder();
                }
                return this.builder;
            }
            set {
                this.builder = value;
            }
        }
        
        protected global::System.CodeDom.Compiler.CompilerErrorCollection Errors {
            get {
                if ((this.errors == null)) {
                    this.errors = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errors;
            }
        }
        
        public string CurrentIndent {
            get {
                return this.currentIndent;
            }
        }
        
        private global::System.Collections.Generic.Stack<int> Indents {
            get {
                if ((this.indents == null)) {
                    this.indents = new global::System.Collections.Generic.Stack<int>();
                }
                return this.indents;
            }
        }
        
        public ToStringInstanceHelper ToStringHelper {
            get {
                return this._toStringHelper;
            }
        }
        
        public void Error(string message) {
            this.Errors.Add(new global::System.CodeDom.Compiler.CompilerError(null, -1, -1, null, message));
        }
        
        public void Warning(string message) {
            global::System.CodeDom.Compiler.CompilerError val = new global::System.CodeDom.Compiler.CompilerError(null, -1, -1, null, message);
            val.IsWarning = true;
            this.Errors.Add(val);
        }
        
        public string PopIndent() {
            if ((this.Indents.Count == 0)) {
                return string.Empty;
            }
            int lastPos = (this.currentIndent.Length - this.Indents.Pop());
            string last = this.currentIndent.Substring(lastPos);
            this.currentIndent = this.currentIndent.Substring(0, lastPos);
            return last;
        }
        
        public void PushIndent(string indent) {
            this.Indents.Push(indent.Length);
            this.currentIndent = (this.currentIndent + indent);
        }
        
        public void ClearIndent() {
            this.currentIndent = string.Empty;
            this.Indents.Clear();
        }
        
        public void Write(string textToAppend) {
            this.GenerationEnvironment.Append(textToAppend);
        }
        
        public void Write(string format, params object[] args) {
            this.GenerationEnvironment.AppendFormat(format, args);
        }
        
        public void WriteLine(string textToAppend) {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendLine(textToAppend);
        }
        
        public void WriteLine(string format, params object[] args) {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendFormat(format, args);
            this.GenerationEnvironment.AppendLine();
        }
        
        public class ToStringInstanceHelper {
            
            private global::System.IFormatProvider formatProvider = global::System.Globalization.CultureInfo.InvariantCulture;
            
            public global::System.IFormatProvider FormatProvider {
                get {
                    return this.formatProvider;
                }
                set {
                    if ((value != null)) {
                        this.formatProvider = value;
                    }
                }
            }
            
            public string ToStringWithCulture(object objectToConvert) {
                if ((objectToConvert == null)) {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                global::System.Type type = objectToConvert.GetType();
                global::System.Type iConvertibleType = typeof(global::System.IConvertible);
                if (iConvertibleType.IsAssignableFrom(type)) {
                    return ((global::System.IConvertible)(objectToConvert)).ToString(this.formatProvider);
                }
                global::System.Reflection.MethodInfo methInfo = type.GetMethod("ToString", new global::System.Type[] {
                            iConvertibleType});
                if ((methInfo != null)) {
                    return ((string)(methInfo.Invoke(objectToConvert, new object[] {
                                this.formatProvider})));
                }
                return objectToConvert.ToString();
            }
        }
    }
}
